apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    Location: Bangladesh
  template:
    metadata:
      name: testpod6
      labels:
        Location: Bangladesh
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo ReplicationController Example; sleep 5 ; done"] 