apiVersion: v1
kind: Pod 
metadata:
  name: day11
  labels:
    env: testing
    deaprtment: DevOps
spec:
  containers: 
    - name: container1
      image: nginx
    - name: container2
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo This is Day11 of 30DaysOfKubernetes; sleep 5 ; done"]
      ports:
        - containerPort: 80