apiVersion: v1
kind: Service                             
metadata:
  name: httpd-service
spec:
  ports:
    - port: 80                               
      targetPort: 80                     
  selector:
    name: DevOps                    
  type: ClusterIP 