apiVersion: v1
kind: Pod
metadata:
  name: nodelabels
  labels:
    env: testing
spec:
  containers:
    - name: container1
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Node-Selecrot Example; sleep 5; done"]
  nodeSelector:
    hardware: t2-medium 