apiVersion: v1
kind: Pod
metadata:
  name: emptydir
spec:
  containers:
  - name: container1
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo This is Day13 of 30DaysOfKubernetes; sleep 5 ; done"]
    volumeMounts:
      - name: day13
        mountPath: "/tmp/container1"
  - name: container2
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo day13 container 2; sleep 5 ; done"]
    volumeMounts:
      - name: day13
        mountPath: "/tmp/container2"
  volumes:
  - name: day13
    emptyDir: {}