apiVersion: v1
kind: Pod
metadata:
  name: initcontainer
spec:
  initContainers:
  - name: initcontainer
    image: ubuntu
    command: ["bin/bash", "-c", "echo We are at 16 days of 30DaysOfKubernete > /tmp/xchange/testfile; sleep 15"]
    volumeMounts:
      - name: xchange 
        mountPath: "/tmp/xchange"
  containers:
  - name: container2
    image: ubuntu
    command: ["bin/bash", "-c" , "while true; do echo `cat /tmp/data/testfile`; sleep 10; done"]
    volumeMounts:
      - name: xchange
        mountPath: /tmp/data/testfile
  volumes:
  - name: xchange
    emptyDir: {}