apiVersion: v1
kind: Pod
metadata:
  name: ns-demo-pod
spec:
  containers: 
  - name: container1
    image: ubuntu
    command: ["bin/bash", "-c", "while true; do echo We are on 18th day of 30daysOfKubernetes; sleep 30; done"]
  restartPolicy: Never