apiVersion: v1
kind: Pod
metadata:
  name: resource
spec: 
  containers:
  - image: ubuntu
    name: res-pod
    command: ["bin/bash", "-c", "while true; do echo We are on 18th Day of 30DaysOfKubernetes; sleep 30; done"]
    resources:
      requests: 
        memory: "32Mi"
        cpu: "200m"
      limits:
        memory: "64Mi"
        cpu: "400m"