apiVersion: batch/v1
kind: CronJob
metadata:
  name: testcronjob
spec: 
  schedule: "* * * * *"
  jobTemplate:
    spec: 
      template: 
        spec: 
          containers: 
            - image: ubuntu
              name: container3
              command: ["bin/bash", "-c", "sudo apt update; sleep 30"]
          restartPolicy: Never