apiVersion: apps/v1
kind: Deployment
metadata: 
  name: thedeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: deploy-pods
  template:
    metadata:
      name: ubuntu-pods
      labels:
        name: deploy-pods
    spec:
      containers:
        - name: container1
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo DevOps is a Culture; sleep 5; done"]